FROM mcr.microsoft.com/devcontainers/typescript-node:0-20
RUN curl -sS https://starship.rs/install.sh | sh -s -- -y
RUN git clone https://github.com/zsh-users/zsh-autosuggestions /home/node/.oh-my-zsh/custom/plugins/zsh-autosuggestions
RUN git clone https://github.com/zsh-users/zsh-syntax-highlighting.git /home/node/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting 
# To install more global node packages
RUN su node -c "npm install -g pnpm@8"